name: Cleanup

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Create config.properties file
        run: echo "${{ secrets.ARCHIVIST_CONFIG }}" | base64 --decode > config.properties
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: shadowJar
      - name: Run
        run: java -jar app/build/libs/app-all.jar --user-id ${{ secrets.ARCHIVIST_USER_ID }} --client-id ${{ secrets.ARCHIVIST_CLIENT_ID }} --client-secret ${{ secrets.ARCHIVIST_CLIENT_SECRET }}
